-- MySQL Script generated by MySQL Workbench
-- mar 04 abr 2023 23:06:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema losses_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema losses_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `losses_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `losses_db` ;

-- -----------------------------------------------------
-- Table `losses_db`.`substance_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`substance_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`substances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`substances` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `A` FLOAT NULL DEFAULT NULL,
  `B` FLOAT NULL DEFAULT NULL,
  `pm_vapor` FLOAT NULL DEFAULT NULL,
  `pm_liquid` FLOAT NULL DEFAULT NULL,
  `Kc` FLOAT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `substance_groups_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_substances_substance_groups1_idx` (`substance_groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_substances_substance_groups1`
    FOREIGN KEY (`substance_groups_id`)
    REFERENCES `losses_db`.`substance_groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`tanks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`tanks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `cp` VARCHAR(100) NOT NULL,
  `isolated` TINYINT(1) NOT NULL,
  `ep` VARCHAR(100) NOT NULL,
  `sr` DECIMAL(10,0) NOT NULL,
  `d` INT NOT NULL,
  `pr` TINYINT(1) NOT NULL DEFAULT '0',
  `ge` TINYINT(1) NOT NULL,
  `hnx` DECIMAL(10,6) NOT NULL,
  `hnn` DECIMAL(10,6) NOT NULL,
  `hs` INT NOT NULL,
  `alfa` DECIMAL(10,6) NOT NULL,
  `hro` DECIMAL(10,6) NOT NULL,
  `tc` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`measurements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`measurements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `substances_id` INT NOT NULL,
  `tanks_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurements_substances1_idx` (`substances_id` ASC) VISIBLE,
  INDEX `fk_measurements_tanks1_idx` (`tanks_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurements_substances1`
    FOREIGN KEY (`substances_id`)
    REFERENCES `losses_db`.`substances` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measurements_tanks1`
    FOREIGN KEY (`tanks_id`)
    REFERENCES `losses_db`.`tanks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1441
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`unit_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`unit_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `symbol` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `unit_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_units_unit_types1_idx` (`unit_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_units_unit_types1`
    FOREIGN KEY (`unit_types_id`)
    REFERENCES `losses_db`.`unit_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`value_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`value_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`measurement_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`measurement_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `value_types_id` INT NOT NULL,
  `measurements_id` INT NOT NULL,
  `units_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurements_data_value_types1_idx` (`value_types_id` ASC) VISIBLE,
  INDEX `fk_measurement_data_measurements1_idx` (`measurements_id` ASC) VISIBLE,
  INDEX `fk_measurement_data_units1_idx` (`units_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurement_data_measurements1`
    FOREIGN KEY (`measurements_id`)
    REFERENCES `losses_db`.`measurements` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measurement_data_units1`
    FOREIGN KEY (`units_id`)
    REFERENCES `losses_db`.`units` (`id`),
  CONSTRAINT `fk_measurements_data_value_types1`
    FOREIGN KEY (`value_types_id`)
    REFERENCES `losses_db`.`value_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2881
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`meteorologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`meteorologies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `month` VARCHAR(45) NOT NULL,
  `I` DECIMAL(10,6) NOT NULL,
  `tmax` DECIMAL(10,6) NOT NULL,
  `tmin` DECIMAL(10,6) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `losses_db`.`losses_oil_gas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`losses_oil_gas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `losses_oil_gascol` DATETIME NOT NULL,
  `lt_oil_gas` DECIMAL(10,6) NOT NULL,
  `tla_oil_gas` DECIMAL(10,6) NOT NULL,
  `tb_oil_gas` DECIMAL(10,6) NOT NULL,
  `hl_oil_gas` DECIMAL(10,6) NOT NULL,
  `pva_oil_gas` DECIMAL(10,6) NOT NULL,
  `taa_oil_gas` DECIMAL(10,6) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` VARCHAR(45) NULL,
  `tanks_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_losses_oil_gas_tanks1_idx` (`tanks_id` ASC) VISIBLE,
  CONSTRAINT `fk_losses_oil_gas_tanks1`
    FOREIGN KEY (`tanks_id`)
    REFERENCES `losses_db`.`tanks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
