-- MySQL Script generated by MySQL Workbench
-- jue 23 mar 2023 22:28:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema losses_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema losses_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `losses_db` ;
USE `losses_db` ;

-- -----------------------------------------------------
-- Table `losses_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`substance_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`substance_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`substances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`substances` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `A` FLOAT NULL,
  `B` FLOAT NULL,
  `pm_vapor` FLOAT NULL,
  `pm_liquid` FLOAT NULL,
  `Kc` FLOAT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL,
  `substance_groups_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_substances_substance_groups1_idx` (`substance_groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_substances_substance_groups1`
    FOREIGN KEY (`substance_groups_id`)
    REFERENCES `losses_db`.`substance_groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`value_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`value_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`tanks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`tanks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `cp` VARCHAR(100) NULL,
  `isolated` TINYINT(1) NULL,
  `ep` VARCHAR(100) NULL,
  `sr` DECIMAL NULL,
  `d` DECIMAL NULL,
  `pr` TINYINT(1) NOT NULL DEFAULT 0,
  `ge` TINYINT(1) NULL,
  `hnx` DECIMAL NULL,
  `hnn` DECIMAL NULL,
  `hs` DECIMAL NULL,
  `alfa` DECIMAL NULL,
  `hro` DECIMAL NULL,
  `tc` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`measurements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`measurements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `substances_id` INT NOT NULL,
  `tanks_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurements_substances1_idx` (`substances_id` ASC) VISIBLE,
  INDEX `fk_measurements_tanks1_idx` (`tanks_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurements_substances1`
    FOREIGN KEY (`substances_id`)
    REFERENCES `losses_db`.`substances` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measurements_tanks1`
    FOREIGN KEY (`tanks_id`)
    REFERENCES `losses_db`.`tanks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`unit_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`unit_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `unit_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_units_unit_types1_idx` (`unit_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_units_unit_types1`
    FOREIGN KEY (`unit_types_id`)
    REFERENCES `losses_db`.`unit_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `losses_db`.`measurement_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losses_db`.`measurement_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `value_types_id` INT NOT NULL,
  `measurements_id` INT NOT NULL,
  `units_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurements_data_value_types1_idx` (`value_types_id` ASC) VISIBLE,
  INDEX `fk_measurement_data_measurements1_idx` (`measurements_id` ASC) VISIBLE,
  INDEX `fk_measurement_data_units1_idx` (`units_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurements_data_value_types1`
    FOREIGN KEY (`value_types_id`)
    REFERENCES `losses_db`.`value_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measurement_data_measurements1`
    FOREIGN KEY (`measurements_id`)
    REFERENCES `losses_db`.`measurements` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_measurement_data_units1`
    FOREIGN KEY (`units_id`)
    REFERENCES `losses_db`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
